source "http://rubygems.org"
gem "pry"
gem "rake"
gem "cucumber", ">0"
gem "rspec", ">0"
gem "watir-webdriver", ">0"
gem "watir-page-helper", ">0"
gem "headless", ">0"
gem "celerity" 
gem "watir", :platforms => [:mswin, :mingw]
